export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST'
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS'
export const GET_LINKS_ERROR = 'GET_LINKS_ERROR'

export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
export const DELETE_LINK_ERROR = 'DELETE_LINK_ERROR'

export const SAVE_LINK_REQUEST = 'SAVE_LINK_REQUEST'
export const SAVE_LINK_SUCCESS = 'SAVE_LINK_SUCCESS'
export const SAVE_LINK_ERROR = 'SAVE_LINK_ERROR'

export const EDIT_LINK = 'EDIT_LINK'
export const EDIT_LINK_CANCEL = 'EDIT_LINK_CANCEL'
